channels:
- conda-forge
- defaults
dependencies:
- abtem=1.0.6
- atomap=0.4.2
- exspy=0.3.2
- ipykernel=7.0.0
- numpy=1.26.4
- python=3.11.14
- scikit-image=0.25.2
# Can include torch=2.5.1 when needed.
name: apdd
